### ISSUE TITLE
Add energy to dual marker stats

### ISSUE THREAD

**Issue by blackenstock** [jetperch/pyjoulescope_ui#145]
Dual marker stat is missing the energy value for the given time range.

**Comment by mliberty1** [comment]
Hi @blackenstock!

The dual markers display the integration for current and power, which is charge and energy, respectively.  Here is an example:
![image](https://user-images.githubusercontent.com/5393422/159258626-a521f6fd-1d5a-4414-97bd-9a2830c62a55.png)

In order to display energy, you do need to enable the `power` waveform.  Does this work for you?

The information displayed with the dual markers is not very customizable at this time with Joulescope UI 0.9.11.  However, we do plan to make some improvements this year.  Check out [this forum post](https://forum.joulescope.com/t/cursor-times-and-delta-t-enhancement/427/2) which contains a summary of all these issues.

**Comment by mliberty1** [comment]
Hi @blackenstock - Did my previous post address the issue?  Since I haven't heard a reply, I am going to assume so and close this issue.  Please reopen it if the response does not fully address the issue!
