### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by atsju** [jetperch/pyjoulescope_ui#148]
Hi,
It seems like the main entry point for your product is the forum and then mostly you @mliberty1 create issues. 
If it's also allowed to add issues/questions directly to the Github by users then maybe you should consider adding an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). The minimum to ask about would be the UI version.

I'm embedded FW developper and used to open source. If you have any question or remark, feel free to ask.

**Comment by mliberty1** [comment]
Thanks for the feedback @atsju .  It's perfectly fine submitting issues directly to our open source projects here on GitHub.  Many Joulescope customers are more comfortable posting to the forum.  As you noticed, I then often create a corresponding issue in the right project.  

I have not spent time configuring our projects on GitHub.  The "Issue Forms" beta looks interesting.  I would want to collect the Joulescope UI version and platform.  As you can see from my issues, I tend to have at least two sections: **Description** and **Expected Behavior**.

Our bug volume and number of collaborators have both been fairly low, so the existing process has been good enough.  However, I should set aside some time to improve things!  I'll keep this open as a reminder.

**Comment by atsju** [comment]
Thanks a lot for all your feedbacks on all issues.  
Consider adding "good first issue" to this one and #146. It's used to flag easy improvements for external contributors. 
I didn't know the "issue template", it seems pretty cool. I might create the thing if I find time and motivation.

**Comment by mliberty1** [comment]
Thank you @atsju for this improvement!
