### ISSUE TITLE
Different energy sum in DualMarker and overall stats

### ISSUE THREAD

**Issue by blackenstock** [jetperch/pyjoulescope_ui#181]
### Joulescope serial number

000412

### UI version

0.10.13

### What OS are you seeing the problem on?

Windows 10

### What happened?

When I record a current consumption and put a dual marker where I want to measure a peak I see different max values for the current consumption dI=6mA (DualMarker shows 133mA max, Overall stats shows 127mA max, single marker shows also 127mA).
UI version 0.10.12.
Recorded in the [UI.](url)

### What was expected?

Same value for dual marker and overall stats.

### How to reproduce?

1. ...
2. ...
3. ...

**Comment by mliberty1** [comment]
Hi @blackenstock - At this point, we will not be fixing any issues in 0.10.x.  Can you try out the 1.0.x alpha [[download](https://download.joulescope.com/joulescope_install/index_v2.html)]?  We completely changed how statistics are computed between 0.10.x and 1.0.x.  Our testing so far looks good, but I would be very interested if you could duplicate this issue on 1.0.x.

**Comment by mliberty1** [comment]
Fixed in 1.0.14 and likely earlier versions.

Here is an example where I manually moved the dual markers to the full extents after setting the right marker to display stats on the left:

![image](https://github.com/jetperch/pyjoulescope_ui/assets/5393422/680140b1-4f05-44a2-9fb2-9cf5006f99df)

I am closing this issue since @blackenstock never reported the issue under 1.0.x.   Since 1.0.x uses a completely different method to compute these values, this issue no longer applies.  If anyone notices discrepancies between dual markers and the right-hand signal statistics, please open a new issue for 1.0.x.
