### ISSUE TITLE
UI user experience feedback

### ISSUE THREAD

**Issue by atsju** [jetperch/pyjoulescope_ui#225]
### Joulescope model

JS220, JS110

### UI version

1.0.29

### Your idea

The behavior of 3 last icons on the left is bothering me more and more when I use them
![image](https://github.com/jetperch/pyjoulescope_ui/assets/4628382/a9aa74b1-70f6-451c-b78c-4288773ea5e7)

- settings : click multiple times will open multiple windows. Settings should only open once I suppose
- memory and device control: either the graph windows should shrink when the side bar opens or the side bar should at lease close automatically when clicking anywhere. The behavior should probably be like in various IDEs, pinning possible and shrinking center widget but not mandatory and shrink itself automatically

**Comment by mliberty1** [comment]
For terminology, we call the bar with the icons on the left the **sidebar**.  The widgets that appear and disappear when you press buttons on the **sidebar** are displayed on the **flyout**.
![image](https://github.com/jetperch/pyjoulescope_ui/assets/5393422/ebd85635-a18b-417b-8ce8-2f87d4231898)

Our initial concept was to have a fixed width **flyout**.  Unfortunately, we could not figure out a nice way to get the Settings widget to display nicely on a reasonably sized **flyout**, which is why the current UI pops up a new floating Settings widget.  I agree that this behavior is annoying.  I think we can change this to make the **flyout** variable width.  We could use a larger width for the Settings widget.  What do you think?

The **flyout** is here to stay as an overlay.  We cannot resize the contained widgets.  Both the Multimeter widget and Waveform widget do not like getting resized too small.  Growing the entire application window to fit both the **flyout** and existing widgets would be considered rude, too.

I agree that a click anywhere other than the **flyout** should close the **flyout**.  We originally had reasons not to do this, but I think that they all went away when we migrated to the [Qt Advanced Docking System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System).

If you want to pin one of these widgets, you simply open it using the Widgets menu.  You can then position the widget to the left side.

Summary of proposed changes:
* Clicking **sidebar** settings should display the **Settings** widget in the **flyout** with a larger width.
* When the **flyout** is showing, clicking anywhere other than the **flyout** should close the **flyout**

What do you think?

**Comment by atsju** [comment]
> Clicking sidebar settings should display the Settings widget in the flyout with a larger width.

About settings, I have no issue that it opens a new widget. Just ensure it can open only one and not several at a time. If one is already open, bring it to front. (This is how I see it). No need to put in into flyout.

An other solution would be to remove settings from the side bar and keep it in menu bar. That's only matter of taste.

> When the flyout is showing, clicking anywhere other than the flyout should close the flyout

Yes please. This is the minimum.

And going further, you said that those flyout menu can be docked to left going through widgets menu. So everything needed to have a "pin" icon is already present in software. You might add a "pin" icon that would then dock it there while resizing the central area. I don't think this is absolutely necessary.


To be honest I find your "waveform" widget very ergonomic.  
The side bar however is unusual. I would only keep things that really need quick access. Removing help, "additional settings", settings, ... and anything that is not everyday use for end users. I see no issue to use the menu bar to access things, unless you target touchscreen applications. Maybe it's only matter of taste. You need to make best choice according to most users feedbacks.

**Comment by mliberty1** [comment]
Addressed in 1.0.35.
