### ISSUE TITLE
Black Screenshot with "copy image to clipboard"

### ISSUE THREAD

**Issue by Nono-73** [jetperch/pyjoulescope_ui#239]
### Joulescope model

JS110

### UI version

other

### What OS are you seeing the problem on?

Windows 10

### What happened?

I have Joulescope_UI 1.0.42. 
When I take screenshot (with 'right-click'->'copy image to clipboard') and I paste it, the screenshot is a black screen : 
![image](https://github.com/jetperch/pyjoulescope_ui/assets/112651669/3d137476-9de9-4dc0-bb33-2e0989883531)
but in reality I have this : 
![image](https://github.com/jetperch/pyjoulescope_ui/assets/112651669/d8c27d8c-c3a3-4253-b126-88774b05c3a6)
**But** if I display a second measure, like current, the 'copy image to clipaboard' work fine : 
![image](https://github.com/jetperch/pyjoulescope_ui/assets/112651669/a1da0a32-8d94-4ff8-bf60-fd9a5b4a04c2)

### What was expected?

Use 'copy image to clipboard' even when there is a measurement displayed

### How to reproduce?

1. Display just one measure (voltage for example)
2. Right-Click -> 'copy image to clipboard'
3. paste it

**Comment by mliberty1** [comment]
Hi @Nono-73 and thanks for reporting this issue.  I was able to successfully duplicate the behavior, except I find that it is always a black image on my PC.  

After investigating, it looks like the image capture takes place immediately.  However, if you were just moving the mouse, the image could have still be rendering.  The fix is to defer the image capture until the next render completes.  The fix is in https://github.com/jetperch/pyjoulescope_ui/commit/a617e595f6eec5ee10b48c21f9174bc2af750ae5 which will be in the next UI release.
