### ISSUE TITLE
Waveform not working with two Joulescopes

### ISSUE THREAD

**Issue by foofel** [jetperch/pyjoulescope_ui#262]
### Joulescope model

JS220

### UI version

1.0.58

### What OS are you seeing the problem on?

Linux Ubuntu amd64 (PC), Other (describe below)

### What happened?

When i connect a second Joulescope i can see it under settings/devices and also read it with e.g. multiple multimeter views. But when using the Waveform i only see the options "default", "off", "off" and "off" while the joulescope is actually running. 
![image](https://github.com/jetperch/pyjoulescope_ui/assets/2386129/95f9e206-d3e3-47df-aa60-1558b5bd7653)

### What was expected?

Show two joulescopes in the waveform widget.

### How to reproduce?

Connect two joulescopes and try to get them both to show in the waveform widget.

**Comment by mliberty1** [comment]
Hi @foofel - In order to select the instrument for each trace, you have to right-click on the Waveform source, like this:

![image](https://github.com/jetperch/pyjoulescope_ui/assets/5393422/5603f1fd-3f18-4d36-a331-3b6cc7d8b985)

Note that left-clicking selects the active source, which is used for the right-hand side statistics and marker statistics.

Does this work for you?

**Comment by foofel** [comment]
Awesome, thanks!
