### ISSUE TITLE
Add an "Are you sure you want to delete all your annotations ?" when "Delete all" is clicked 

### ISSUE THREAD

**Issue by Chloeplt** [jetperch/pyjoulescope_ui#287]
### Joulescope model

JS220

### UI version

1.1.9

### Your idea

"Delete all" is really close by "Text" option, which can cause a missclick and, so on, the lost of all the added annotations.
Adding a question as "Are you sure you want to delete all your annotations ?" after the click could be usefull.

![image](https://github.com/user-attachments/assets/9b8af2e5-102c-4e4a-9b70-1ac1278429e0)

**Comment by mliberty1** [comment]
We already have a way to save you from any error like this.  Use the "undo" function.  On Windows, press `CTRL-Z.`  To redo, press `CTRL-Y` or `CTRL-SHIFT-Z`.

We could do better to make the undo/redo feature more discoverable, but it is there!

I am not a fan of confirmation dialogs as people tend to just click through them without thinking, especially since undo/redo works well.

I am going to close this issue, but please reopen if undo / redo does not work for you!
