### ISSUE TITLE
Waveform Y-Axis zoom only zooms out with trackpad

### ISSUE THREAD

**Issue by seanboothm** [jetperch/pyjoulescope_ui#70]
On manual range for the y-axis in waveform view, the user uses the mouse scroll wheel to zoom in and out. With a normal mouse this works as intended, but with a laptop trackpad (tested both on my HP laptop, and a coworker's macbook) the interface only seems to scroll out, no matter which direction the trackpad scroll is performed. 

![js y axis scroll](https://user-images.githubusercontent.com/6071700/78377862-cdb52880-7595-11ea-919b-90b931a217b3.gif)

**Comment by mliberty1** [comment]
Hi @seanboothm and thank you for the very clear demonstration of this issue.  I was able to easily duplicate this issue on my laptop.  The underlying cause was that pyqtgraph's y-axis range setting adds a "padding" by default.  The fix was to force padding of zero.  The fix is now in the develop branch and will be in the next official release.  Thank you!
